version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    
    

